#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

printf "========= ${RED}work${NC} | ${GREEN}personal${NC} =========\n"
printf "${RED}1. VPN\n2. Akamai\n3. AWS\n4. Slack\n5. Divvy\n6. Google\n${GREEN}7. AWS\n8. Facebook\n9. npm\n10. bitwarden\n11. stripe\n12. uphold\n${NC}Enter a number to generate an otp: "
read input
echo
if [ $input = 1 ]; then
  oathtool -b --totp ''
elif [ $input = 2 ]; then
  oathtool -b --totp ''
elif [ $input = 3 ]; then
  oathtool -b --totp ''
elif [ $input = 4 ]; then
  oathtool -b --totp ''
elif [ $input = 5 ]; then
  oathtool -b --totp ''
elif [ $input = 6 ]; then
  oathtool -b --totp ''
elif [ $input = 7 ]; then
  oathtool -b --totp ''
elif [ $input = 8 ]; then
  oathtool -b --totp ''
elif [ $input = 9 ]; then
  oathtool -b --totp ''
elif [ $input = 10 ]; then
  oathtool -b --totp ''
elif [ $input = 11 ]; then
  oathtool -b --totp ''
elif [ $input = 12 ]; then
  oathtool -b --totp ''
else
  echo "No valid number found"
fi
echo